import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Breadcrumbs } from "@/components/seo/breadcrumbs";
import { PageHero } from "@/components/sections/page-hero";
import { ProductionCapabilitiesSection } from "@/components/sections/production-capabilities-section";
import { media } from "@/content/media";
import { buildPageMetadata } from "@/lib/cms-seo";
import { isLocale, localizePath, type Locale } from "@/lib/i18n";
import { ensureSiteConfig } from "@/sanity/load-site-config";

type PageProps = { params: Promise<{ locale: string }> };
export async function generateMetadata({ params }: PageProps): Promise<Metadata> { const { locale } = await params; if (!isLocale(locale)) return {}; await ensureSiteConfig(); return buildPageMetadata({ path: "/production-capabilities", locale, fallbackTitle: locale === "ar" ? "CPS — قدرات الإنتاج" : "CPS — Production Capabilities", fallbackDescription: locale === "ar" ? "منشأة إنتاج متكاملة للخشب والمعدن والأكريليك والطباعة والتركيب." : "One integrated production floor for wood, metal, acrylic, print and installation." }); }
export default async function ProductionCapabilitiesPage({ params }: PageProps) { const { locale: value } = await params; if (!isLocale(value)) notFound(); const locale: Locale = value; const ar = locale === "ar"; return <><Breadcrumbs locale={locale} items={[{ label: ar ? "الرئيسية" : "Home", href: "/" }, { label: ar ? "قدرات الإنتاج" : "Production Capabilities" }]} /><PageHero eyebrow={ar ? "قدرات الإنتاج" : "Production Capabilities"} title={ar ? "ما نسلّمه مدعوم بكيفية تصنيعه." : "What we deliver is supported by how we build it."} lead={ar ? "منشأة واحدة تجمع الحرفة والتقنية والتجميع والتركيب." : "One production floor connects craft, technology, assembly and on-site installation."} image={media.about.studio} imageAlt={ar ? "منشأة إنتاج CPS" : "CPS production facility"} cta={{ label: ar ? "ابدأ مشروعاً" : "Start a Project", href: localizePath("/contact", locale) }} /><section className="capability-explainer section-pad"><div className="site-container"><p className="eyebrow">{ar ? "الخدمة مقابل القدرة" : "Service vs Capability"}</p><h2>{ar ? "الخدمة هي ما نسلّمه. القدرة هي كيف نصنعه." : "A service is what we deliver. A capability is how we build it."}</h2><div className="capability-explainer-grid"><article><h3>{ar ? "الخدمات" : "Services"}</h3><p>{ar ? "ثمانية مسارات واضحة تبدأ من احتياج العميل وتنتهي بنتيجة جاهزة للاستخدام." : "Eight clear offers that begin with a client need and end with a finished outcome."}</p></article><article><h3>{ar ? "قدرات الإنتاج" : "Production capabilities"}</h3><p>{ar ? "التخصصات والعمليات الداخلية المشتركة التي تدعم كل خدمة وتحافظ على الجودة." : "The shared in-house disciplines and processes that support every service and control quality."}</p></article></div></div></section><ProductionCapabilitiesSection locale={locale} standalone /><section className="service-closing"><div className="site-container"><h2>{ar ? "لنبنِ مشروعك تحت سقف واحد." : "Let us build your project under one roof."}</h2><Link href={localizePath("/contact", locale)} className="btn-primary">{ar ? "ابدأ مشروعاً" : "Start a Project"}</Link></div></section></>; }
