import type { Project } from "@/content/projects";

type CloudinaryProjectInput = {
  projectCode: string;
  cloudinaryFolder: string;
  slug: string;
  year: string;
  clientName: { en: string; ar: string };
  title: { en: string; ar: string };
  kind: keyof typeof copyByKind;
  image: string;
  gallery: string[];
  motionVideo?: string;
  industrySlug?: string;
  locationSlug?: string;
  event?: string;
  size?: string;
  featured?: boolean;
};

const copyByKind = {
  booth: {
    categoryEn: "Exhibition Booth",
    categoryAr: "جناح معارض",
    scopeEn: "Booth fabrication, branded finishes, large-format graphics, lighting and on-site installation.",
    scopeAr: "تصنيع الجناح والتشطيبات المرتبطة بالهوية والطباعة كبيرة الحجم والإضاءة والتركيب في الموقع.",
    challengeEn: "Translate the brand into a distinctive, practical show-floor environment while meeting venue, schedule and visitor-flow requirements.",
    challengeAr: "تحويل الهوية إلى بيئة معرض مميزة وعملية مع الالتزام بمتطلبات الموقع والجدول وحركة الزوار.",
    approachEn: "CPS coordinated detailing, fabrication, graphics and site delivery as one production workflow, resolving the build before installation.",
    approachAr: "نسّقت سي بي إس التفاصيل والتصنيع والطباعة والتسليم الموقعي ضمن مسار إنتاج واحد، مع حل تفاصيل التنفيذ قبل التركيب.",
    outcomeEn: "A polished exhibition presence delivered as a complete, installation-ready environment.",
    outcomeAr: "حضور متكامل ومصقول في المعرض تم تسليمه كبيئة جاهزة للتشغيل.",
  },
  event: {
    categoryEn: "Event Fabrication",
    categoryAr: "تجهيز فعاليات",
    scopeEn: "Event structures, branded scenic elements, graphics, fabrication, delivery and installation.",
    scopeAr: "هياكل الفعالية والعناصر الديكورية المرتبطة بالهوية والطباعة والتصنيع والتوصيل والتركيب.",
    challengeEn: "Deliver a branded event environment to a fixed opening date while coordinating structure, finishes and site constraints.",
    challengeAr: "تسليم بيئة فعالية متكاملة الهوية في موعد افتتاح ثابت مع تنسيق الهيكل والتشطيبات ومتطلبات الموقع.",
    approachEn: "CPS developed the production details, fabricated the physical elements in-house and coordinated the on-site build.",
    approachAr: "طورت سي بي إس تفاصيل الإنتاج وصنعت العناصر داخلياً ونسّقت التنفيذ في الموقع.",
    outcomeEn: "A cohesive event setting delivered on schedule and ready for guests and programme operations.",
    outcomeAr: "بيئة فعالية متناسقة تم تسليمها في الموعد وجاهزة لاستقبال الضيوف وتشغيل البرنامج.",
  },
  branding: {
    categoryEn: "Branding & Production",
    categoryAr: "هوية وإنتاج",
    scopeEn: "Branded production, graphics, finishing, packing and coordinated delivery.",
    scopeAr: "إنتاج العناصر المرتبطة بالهوية والطباعة والتشطيب والتعبئة والتسليم المنسق.",
    challengeEn: "Maintain consistent brand quality across a production run while meeting delivery and handling requirements.",
    challengeAr: "الحفاظ على جودة وهوية متسقة عبر كامل الكمية مع الالتزام بمتطلبات التسليم والتداول.",
    approachEn: "CPS standardised materials, print output and finishing checks before packing and dispatch.",
    approachAr: "وحّدت سي بي إس الخامات وجودة الطباعة وفحوصات التشطيب قبل التعبئة والإرسال.",
    outcomeEn: "A consistent branded collection prepared for reliable distribution and use.",
    outcomeAr: "مجموعة متناسقة الهوية وجاهزة للتوزيع والاستخدام بكفاءة.",
  },
  retail: {
    categoryEn: "Retail Displays",
    categoryAr: "تجهيزات عرض تجزئة",
    scopeEn: "Retail fixture fabrication, branded graphics, finishing and multi-site installation.",
    scopeAr: "تصنيع وحدات العرض والتجهيزات والرسومات المرتبطة بالهوية والتشطيب والتركيب في المواقع.",
    challengeEn: "Create durable, repeatable fixtures that present products clearly across active retail and pharmacy locations.",
    challengeAr: "إنتاج وحدات متينة وقابلة للتكرار تعرض المنتجات بوضوح داخل المتاجر والصيدليات العاملة.",
    approachEn: "CPS standardised the fixture build, finishes and graphic application for consistent deployment.",
    approachAr: "وحّدت سي بي إس تصنيع الوحدات والتشطيبات وتطبيق الهوية لضمان تنفيذ متناسق.",
    outcomeEn: "A consistent retail display system installed for clear merchandising and everyday operation.",
    outcomeAr: "نظام عرض تجزئة متناسق تم تركيبه لعرض المنتجات بوضوح والاستخدام اليومي.",
  },
  signage: {
    categoryEn: "Stand & Signage",
    categoryAr: "ستاند ولافتات",
    scopeEn: "Stand and backdrop fabrication, branded graphics, finishing, delivery and installation.",
    scopeAr: "تصنيع الستاند والخلفيات والطباعة المرتبطة بالهوية والتشطيب والتوصيل والتركيب.",
    challengeEn: "Produce a compact branded structure with clean visual impact and dependable site execution.",
    challengeAr: "إنتاج هيكل مدمج يعكس الهوية بوضوح مع تنفيذ موقعي دقيق وموثوق.",
    approachEn: "CPS translated approved artwork into production-ready panels and coordinated fabrication and installation.",
    approachAr: "حوّلت سي بي إس التصميمات المعتمدة إلى ألواح جاهزة للإنتاج ونسّقت التصنيع والتركيب.",
    outcomeEn: "A clean, durable branded installation ready for the event programme.",
    outcomeAr: "تركيب متين وواضح الهوية وجاهز لبرنامج الفعالية.",
  },
} as const;

function buildProject(input: CloudinaryProjectInput): Project {
  const copy = copyByKind[input.kind];
  const eventEn = input.event ? ` for ${input.event}` : "";
  const eventAr = input.event ? ` ضمن ${input.event}` : "";

  return {
    projectCode: input.projectCode,
    cloudinaryFolder: input.cloudinaryFolder,
    slug: input.slug,
    year: input.year,
    image: input.image,
    imageAlt: `${input.title.en} — CPS project`,
    gallery: input.gallery,
    motionVideo: input.motionVideo,
    industrySlug: input.industrySlug,
    serviceSlug: serviceByKind[input.kind].primary,
    serviceSlugs: [...serviceByKind[input.kind].all],
    boothTypeSlug: input.kind === "booth" ? "custom" : undefined,
    locationSlug: input.locationSlug,
    event: input.event,
    size: input.size,
    technologies: [...serviceByKind[input.kind].tech],
    featured: input.featured,
    clientName: input.clientName,
    en: {
      title: input.title.en,
      category: copy.categoryEn,
      summary: `A ${copy.categoryEn.toLowerCase()} produced and delivered by CPS for ${input.clientName.en}${eventEn}.`,
      scopeOfWork: copy.scopeEn,
      challenge: copy.challengeEn,
      approach: copy.approachEn,
      outcome: copy.outcomeEn,
    },
    ar: {
      title: input.title.ar,
      category: copy.categoryAr,
      summary: `مشروع ${copy.categoryAr} نفذته وسلمته سي بي إس لصالح ${input.clientName.ar}${eventAr}.`,
      scopeOfWork: copy.scopeAr,
      challenge: copy.challengeAr,
      approach: copy.approachAr,
      outcome: copy.outcomeAr,
    },
  };
}

const serviceByKind = {
  booth: {
    primary: "exhibitions-booths",
    all: ["exhibitions-booths","custom-fabrication","printing-signage","installation-project-delivery"],
    booth: "custom",
    tech: ["Custom fabrication","Large-format graphics","Integrated lighting","On-site installation"],
  },
  event: {
    primary: "event-fabrication",
    all: ["event-fabrication","custom-fabrication","printing-signage","installation-project-delivery"],
    tech: ["Event structures","Branded finishes","Large-format graphics","Site installation"],
  },
  branding: {
    primary: "printing-signage",
    all: ["printing-signage","custom-fabrication","installation-project-delivery"],
    tech: ["Branded fabrication","Large-format printing","Finishing","On-site delivery"],
  },
  retail: {
    primary: "retail-displays",
    all: ["retail-displays","custom-fabrication","printing-signage","installation-project-delivery"],
    tech: ["Retail display fabrication","Metalwork","Branded graphics","Installation"],
  },
  signage: {
    primary: "printing-signage",
    all: ["printing-signage","custom-fabrication","installation-project-delivery"],
    tech: ["Large-format printing","Custom joinery","Branded finishes","On-site installation"],
  },
} as const;

function videoPoster(url: string): string {
  return url
    .replace("/video/upload/", "/video/upload/so_0/f_jpg/")
    .replace(/\.mp4$/, ".jpg");
}

export const cloudinaryProjects: Project[] = [
  buildProject({
    projectCode: "CBO-1001",
    cloudinaryFolder: "cps/CBO-1001 Ajlan Booth at Mining and Metal Expo Jan 2026",
    slug: "ajlan-mining-metal-expo-2026",
    year: "2026",
    clientName: { en: "Ajlan & Bros", ar: "عجلان وإخوانه" },
    title: { en: "Ajlan Booth — Mining & Metal Expo 2026", ar: "جناح عجلان — معرض التعدين والمعادن 2026" },
    kind: "booth",
    image: "https://res.cloudinary.com/jivfgunl/image/upload/v1789256139/IMG-20260109-WA0010.jpg",
    gallery: [
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256139/IMG-20260109-WA0010.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256125/IMG-20260109-WA0021.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256131/WhatsApp_Image_2026-01-09_at_3.27.31_AM.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256069/IMG-20260109-WA0000.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256114/IMG-20260109-WA0001.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256117/IMG-20260109-WA0003.jpg",
    ],
    motionVideo: "https://res.cloudinary.com/jivfgunl/video/upload/v1789256833/0913_1.mp4",
    industrySlug: "real-estate",
    locationSlug: "riyadh",
    event: "Mining & Metal Expo 2026",
    featured: true,
  }),
  buildProject({
    projectCode: "CBO-1003",
    cloudinaryFolder: "cps/CBO-1003 Bufomix Booth 3x3 at STS 2025 international conference - Hail",
    slug: "bufomix-sts-hail-2025",
    year: "2025",
    clientName: { en: "Bufomix", ar: "بوفوميكس" },
    title: { en: "Bufomix Booth — STS Hail 2025", ar: "جناح بوفوميكس — مؤتمر STS حائل 2025" },
    kind: "booth",
    image: "https://res.cloudinary.com/jivfgunl/image/upload/v1789256121/Photo_from_Aevenda_MBE_10.jpg",
    gallery: [
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256121/Photo_from_Aevenda_MBE_10.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256098/Photo_from_Aevenda_MBE_14.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256099/Photo_from_Aevenda_MBE_15.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256106/Photo_from_Aevenda_MBE_7.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256141/Photo_from_Aevenda_MBE_18.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256112/Photo_from_Aevenda_MBE_16.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256099/Photo_from_Aevenda_MBE_17.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256101/Photo_from_Aevenda_MBE_8.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256106/Photo_from_Aevenda_MBE_9.jpg",
    ],
    industrySlug: "healthcare-pharmaceutical",
    event: "STS International Conference 2025",
    size: "3×3 m",
  }),
  buildProject({
    projectCode: "CBO-1004",
    cloudinaryFolder: "cps/CBO-1004 Hikma - Megamox Booth 4x2 - Jeddah",
    slug: "hikma-megamox-jeddah",
    year: "2025",
    clientName: { en: "Hikma — Megamox", ar: "حكمة — ميجاموكس" },
    title: { en: "Hikma Megamox Booth — Jeddah", ar: "جناح حكمة ميجاموكس — جدة" },
    kind: "booth",
    image: "https://res.cloudinary.com/jivfgunl/image/upload/v1789256108/Photo_from_Aevenda_MBE_5.jpg",
    gallery: [
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256108/Photo_from_Aevenda_MBE_5.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256115/Photo_from_Aevenda_MBE_6.jpg",
    ],
    motionVideo: "https://res.cloudinary.com/jivfgunl/video/upload/v1789256297/Video_from_Aevenda_MBE.mp4",
    industrySlug: "healthcare-pharmaceutical",
    locationSlug: "jeddah",
    size: "4×2 m",
  }),
  buildProject({
    projectCode: "CBO-1005",
    cloudinaryFolder: "cps/CBO-1005 Hikma Booth 2x2 at 2nd kidney forum Oct 2025 Riyadh",
    slug: "hikma-kidney-forum-riyadh-2025",
    year: "2025",
    clientName: { en: "Hikma", ar: "حكمة" },
    title: { en: "Hikma Booth — 2nd Kidney Forum 2025", ar: "جناح حكمة — ملتقى الكلى الثاني 2025" },
    kind: "booth",
    image: "https://res.cloudinary.com/jivfgunl/image/upload/v1789256113/IMG-20251023-WA0035.jpg",
    gallery: [
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256113/IMG-20251023-WA0035.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256112/IMG-20251023-WA0036.jpg",
    ],
    industrySlug: "healthcare-pharmaceutical",
    locationSlug: "riyadh",
    event: "2nd Kidney Forum",
    size: "2×2 m",
  }),
  buildProject({
    projectCode: "CBO-1006",
    cloudinaryFolder: "cps/CBO-1006 Meena Booth 5_4 at Riyadh with activation",
    slug: "meena-booth-riyadh",
    year: "2025",
    clientName: { en: "Meena", ar: "مينا" },
    title: { en: "Meena Booth & Activation — Riyadh", ar: "جناح وتفعيل مينا — الرياض" },
    kind: "booth",
    image: "https://res.cloudinary.com/jivfgunl/image/upload/v1789256118/Photo_from_Aevenda_MBE_1.jpg",
    gallery: [
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256118/Photo_from_Aevenda_MBE_1.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256122/Photo_from_Aevenda_MBE_3.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256120/Photo_from_Aevenda_MBE_2.jpg",
    ],
    industrySlug: "retail-shopping-malls",
    locationSlug: "riyadh",
    size: "5×4 m",
  }),
  buildProject({
    projectCode: "CBO-1007",
    cloudinaryFolder: "cps/CBO-1007 Nusuk Booth Jeddah 15x7 Nov 2025",
    slug: "nusuk-booth-jeddah-2025",
    year: "2025",
    clientName: { en: "Nusuk", ar: "نُسُك" },
    title: { en: "Nusuk Booth — Jeddah 2025", ar: "جناح نُسُك — جدة 2025" },
    kind: "booth",
    image: videoPoster("https://res.cloudinary.com/jivfgunl/video/upload/v1789256363/Video_from_Aevenda_MBE_1.mp4"),
    gallery: [
    ],
    motionVideo: "https://res.cloudinary.com/jivfgunl/video/upload/v1789256363/Video_from_Aevenda_MBE_1.mp4",
    industrySlug: "government-public-sector",
    locationSlug: "jeddah",
    event: "Nusuk, November 2025",
    size: "15×7 m",
  }),
  buildProject({
    projectCode: "CBO-1008",
    cloudinaryFolder: "cps/CBO-1008 Riyad Bank and Al Hilal Booths and activations 2025 - 2026",
    slug: "riyad-bank-al-hilal-activations-2025-2026",
    year: "2025–2026",
    clientName: { en: "Riyad Bank & Al Hilal", ar: "بنك الرياض والهلال" },
    title: { en: "Riyad Bank & Al Hilal Booths and Activations", ar: "أجنحة وتفعيلات بنك الرياض والهلال" },
    kind: "booth",
    image: "https://res.cloudinary.com/jivfgunl/image/upload/v1789256074/IMG-20260108-WA0034.jpg",
    gallery: [
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256074/IMG-20260108-WA0034.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256084/IMG-20260108-WA0050.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256078/IMG-20260108-WA0051.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256074/IMG-20260108-WA0033.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256078/IMG-20260108-WA0040.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256076/IMG-20260108-WA0047.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256079/IMG-20260112-WA0008.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256084/IMG-20260112-WA0010.jpg",
    ],
    motionVideo: "https://res.cloudinary.com/jivfgunl/video/upload/v1789256861/Al_Hilal_and_Riyad_Bank_booths_activation_photobooth.mp4",
    industrySlug: "sports-entertainment",
    locationSlug: "riyadh",
    event: "2025–2026 activation programme",
    featured: true,
  }),
  buildProject({
    projectCode: "CBO-1009",
    cloudinaryFolder: "cps/CBO-1009 Sirar Booth 2x2_",
    slug: "sirar-booth-2x2",
    year: "2025",
    clientName: { en: "Sirar", ar: "سايرار" },
    title: { en: "Sirar Booth 2×2", ar: "جناح سايرار 2×2" },
    kind: "booth",
    image: "https://res.cloudinary.com/jivfgunl/image/upload/v1789256128/Photo_from_Aevenda_MBE_4.jpg",
    gallery: [
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256128/Photo_from_Aevenda_MBE_4.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256115/Photo_from_Aevenda_MBE.jpg",
    ],
    industrySlug: "technology-electronics",
    locationSlug: "riyadh",
    size: "2×2 m",
  }),
  buildProject({
    projectCode: "CBO-1010",
    cloudinaryFolder: "cps/CBO-1010 SNB Booth 5x4 Dec 2025 - Laysen Valley Riyadh",
    slug: "snb-booth-laysen-valley-2025",
    year: "2025",
    clientName: { en: "Saudi National Bank", ar: "البنك الأهلي السعودي" },
    title: { en: "SNB Booth — Laysen Valley 2025", ar: "جناح الأهلي السعودي — ليسن فالي 2025" },
    kind: "booth",
    image: "https://res.cloudinary.com/jivfgunl/image/upload/v1789256092/Copy_of_DSC01719.jpg",
    gallery: [
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256092/Copy_of_DSC01719.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256105/Copy_of_DSC01720.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256103/Copy_of_DSC01724.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256098/Copy_of_DSC01713.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256091/Copy_of_DSC01710.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256091/Copy_of_DSC01711.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256072/Copy_of_DSC01714.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256067/IMG-20251211-WA0006.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256068/IMG-20251211-WA0008.jpg",
    ],
    motionVideo: "https://res.cloudinary.com/jivfgunl/video/upload/v1789256855/Document_from_Aevenda_MBE.mp4",
    industrySlug: "banking-financial-services",
    locationSlug: "riyadh",
    event: "Laysen Valley, December 2025",
    size: "5×4 m",
    featured: true,
  }),
  buildProject({
    projectCode: "CBO-1011",
    cloudinaryFolder: "cps/CBO-1011 SNB Quickpay Booth 6x6 and 5x5 with video recording activation",
    slug: "snb-quickpay-booth-activation",
    year: "2025",
    clientName: { en: "SNB Quickpay", ar: "كويك باي من الأهلي السعودي" },
    title: { en: "SNB Quickpay Booth & Video Activation", ar: "جناح كويك باي وتفعيل تسجيل الفيديو" },
    kind: "booth",
    image: "https://res.cloudinary.com/jivfgunl/image/upload/v1789256121/IMG-20251119-WA0041.jpg",
    gallery: [
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256121/IMG-20251119-WA0041.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256069/IMG-20251113-WA0095.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256093/IMG-20251119-WA0029.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256094/IMG-20251119-WA0035.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256115/IMG-20251119-WA0036.jpg",
    ],
    motionVideo: "https://res.cloudinary.com/jivfgunl/video/upload/v1789256837/Zoo_small.mp4",
    industrySlug: "banking-financial-services",
    locationSlug: "riyadh",
    size: "6×6 m and 5×5 m",
    featured: true,
  }),
  buildProject({
    projectCode: "CBR-1001",
    cloudinaryFolder: "cps/CBR-1001 SAB Invest Branding basket for keswet sheta",
    slug: "sab-invest-keswet-sheta-branding",
    year: "2025",
    clientName: { en: "SAB Invest", ar: "الأول للاستثمار" },
    title: { en: "SAB Invest — Keswet Sheta Branding", ar: "الأول للاستثمار — هوية كسوة الشتاء" },
    kind: "branding",
    image: "https://res.cloudinary.com/jivfgunl/image/upload/v1789256067/IMG-20251217-WA0035.jpg",
    gallery: [
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256067/IMG-20251217-WA0035.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256095/IMG-20251217-WA0036.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256094/IMG-20251217-WA0037.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256094/IMG-20251217-WA0038.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256095/IMG-20251217-WA0039.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256097/IMG-20251217-WA0040.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256092/IMG-20251217-WA0041.jpg",
    ],
    industrySlug: "banking-financial-services",
    locationSlug: "riyadh",
  }),
  buildProject({
    projectCode: "CEV-1001",
    cloudinaryFolder: "cps/CEV-1001 Jakaroo Gate Dec 2025",
    slug: "jakaroo-event-gate-2025",
    year: "2025",
    clientName: { en: "Jakaroo", ar: "جاكارو" },
    title: { en: "Jakaroo Event Gate 2025", ar: "بوابة فعالية جاكارو 2025" },
    kind: "event",
    image: "https://res.cloudinary.com/jivfgunl/image/upload/v1789256135/01-26.jpg",
    gallery: [
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256135/01-26.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256098/IMG-20251203-WA0042.jpg",
    ],
    industrySlug: "sports-entertainment",
    locationSlug: "riyadh",
    event: "December 2025",
  }),
  buildProject({
    projectCode: "CEV-1003",
    cloudinaryFolder: "cps/CEV-1003 Riyad Bank Risk Management Nov 2025",
    slug: "riyad-bank-risk-management-2025",
    year: "2025",
    clientName: { en: "Riyad Bank", ar: "بنك الرياض" },
    title: { en: "Riyad Bank Risk Management Event", ar: "فعالية إدارة المخاطر لبنك الرياض" },
    kind: "event",
    image: "https://res.cloudinary.com/jivfgunl/image/upload/v1789256116/IMG-20251111-WA0060.jpg",
    gallery: [
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256116/IMG-20251111-WA0060.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256114/IMG-20251111-WA0069.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256133/IMG-20251111-WA0057.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256140/IMG-20251111-WA0059.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256125/IMG-20251111-WA0063.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256111/IMG-20251111-WA0051.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256097/IMG-20251111-WA0070.jpg",
    ],
    motionVideo: "https://res.cloudinary.com/jivfgunl/video/upload/v1789256154/VID-20251111-WA0039.mp4",
    industrySlug: "banking-financial-services",
    locationSlug: "riyadh",
    event: "Risk Management, November 2025",
    featured: true,
  }),
  buildProject({
    projectCode: "CEV-1004",
    cloudinaryFolder: "cps/CEV-1004 SNB Keshteh Gate Dec 2025",
    slug: "snb-keshteh-gate-2025",
    year: "2025",
    clientName: { en: "Saudi National Bank", ar: "البنك الأهلي السعودي" },
    title: { en: "SNB Keshteh Gate 2025", ar: "بوابة كشتة للأهلي السعودي 2025" },
    kind: "event",
    image: "https://res.cloudinary.com/jivfgunl/image/upload/v1789256120/IMG-20251220-WA0002.jpg",
    gallery: [
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256120/IMG-20251220-WA0002.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256121/IMG-20251220-WA0003.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256112/IMG-20251220-WA0004.jpg",
    ],
    industrySlug: "banking-financial-services",
    locationSlug: "riyadh",
    event: "Keshteh, December 2025",
  }),
  buildProject({
    projectCode: "CEV-1006-A",
    cloudinaryFolder: "cps/CEV-1006 Riyad Bank Molhem Oct 2025",
    slug: "riyad-bank-molhem-2025",
    year: "2025",
    clientName: { en: "Riyad Bank", ar: "بنك الرياض" },
    title: { en: "Riyad Bank Molhem Event 2025", ar: "فعالية ملهم لبنك الرياض 2025" },
    kind: "event",
    image: "https://res.cloudinary.com/jivfgunl/image/upload/v1789256105/IMG-20251102-WA0071.jpg",
    gallery: [
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256105/IMG-20251102-WA0071.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256105/IMG-20251102-WA0072.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256103/IMG-20251102-WA0068.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256093/IMG-20251102-WA0069.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256104/IMG-20251102-WA0070.jpg",
    ],
    industrySlug: "banking-financial-services",
    locationSlug: "riyadh",
    event: "Molhem, October 2025",
  }),
  buildProject({
    projectCode: "CEV-1006-B",
    cloudinaryFolder: "cps/CEV-1006 Tawuniya Mobility May 2026",
    slug: "tawuniya-mobility-2026",
    year: "2026",
    clientName: { en: "Tawuniya", ar: "التعاونية" },
    title: { en: "Tawuniya Mobility 2026", ar: "فعالية التنقل للتعاونية 2026" },
    kind: "event",
    image: videoPoster("https://res.cloudinary.com/jivfgunl/video/upload/v1789256314/Tawuniya_Mobility_Video.mp4"),
    gallery: [
    ],
    motionVideo: "https://res.cloudinary.com/jivfgunl/video/upload/v1789256314/Tawuniya_Mobility_Video.mp4",
    industrySlug: "banking-financial-services",
    locationSlug: "riyadh",
    event: "Mobility, May 2026",
    featured: true,
  }),
  buildProject({
    projectCode: "CRTAL-1001",
    cloudinaryFolder: "cps/CRTAL-1001 Gondola - Stores, Pharmacies Installations",
    slug: "gondola-retail-pharmacy-installations",
    year: "2025",
    clientName: { en: "Gondola", ar: "جوندولا" },
    title: { en: "Gondola Retail & Pharmacy Installations", ar: "تركيبات جوندولا للمتاجر والصيدليات" },
    kind: "retail",
    image: "https://res.cloudinary.com/jivfgunl/image/upload/v1789256114/IMG-20251023-WA0065.jpg",
    gallery: [
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256114/IMG-20251023-WA0065.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256107/IMG-20251023-WA0066.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256107/IMG-20251025-WA0035.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256122/IMG-20251025-WA0036.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256110/IMG-20251025-WA0037.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256108/IMG-20251025-WA0039.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256108/IMG-20251025-WA0042.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256113/IMG-20251025-WA0044.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256108/IMG-20251103-WA0056.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256109/IMG-20251103-WA0057.jpg",
    ],
    industrySlug: "retail-shopping-malls",
    featured: true,
  }),
  buildProject({
    projectCode: "CST-1002",
    cloudinaryFolder: "cps/CST-1002 SNBER  Stand Dec 2025",
    slug: "snber-stand-2025",
    year: "2025",
    clientName: { en: "SNBER", ar: "SNBER" },
    title: { en: "SNBER Stand 2025", ar: "جناح SNBER 2025" },
    kind: "signage",
    image: "https://res.cloudinary.com/jivfgunl/image/upload/v1789256109/IMG-20251211-WA0000.jpg",
    gallery: [
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256109/IMG-20251211-WA0000.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256117/IMG-20251211-WA0001.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256118/IMG-20251211-WA0002.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256121/IMG-20251211-WA0003.jpg",
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256133/IMG-20251211-WA0060.jpg",
    ],
    industrySlug: "banking-financial-services",
    locationSlug: "riyadh",
    event: "December 2025",
  }),
  buildProject({
    projectCode: "CST-1003",
    cloudinaryFolder: "cps/CST-1003 Sirar cybersecurity day Backdrop Oct 2025",
    slug: "sirar-cybersecurity-day-backdrop-2025",
    year: "2025",
    clientName: { en: "Sirar", ar: "سايرار" },
    title: { en: "Sirar Cybersecurity Day Backdrop", ar: "خلفية يوم الأمن السيبراني لسايرار" },
    kind: "signage",
    image: "https://res.cloudinary.com/jivfgunl/image/upload/v1789256128/IMG-20251015-WA0080.jpg",
    gallery: [
      "https://res.cloudinary.com/jivfgunl/image/upload/v1789256128/IMG-20251015-WA0080.jpg",
    ],
    industrySlug: "technology-electronics",
    locationSlug: "riyadh",
    event: "Cybersecurity Day, October 2025",
  }),
];

